name: auto-deploy-to-s3-action
on:
  push:
    paths:
      - endpoints/**
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set env
        run: echo "Lambda_Folder=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -oP '(?<=\/)(.*?)(?=\/)')" >> $GITHUB_ENV
      - name: Call lambda function
        id: githubtos3
        uses: gagoar/invoke-aws-lambda@master
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION: 'us-west-2'
          FunctionName: gitHubToS3
          Payload: '{
            "username": "${{ github.actor }}",
            "token": "${{ github.token }}",
            "repo_name": "etl-api",
            "lambda_folder": "${{ env.Lambda_Folder }}",
            "repo_path": "${{ github.server_url }}/${{ github.repository }}",
            "bucket_name": "d3-capstone-bucket",
            "bucket_key": "api/development/${{ env.Lambda_Folder }}.zip",
            "bucket_body": "${{ env.Lambda_Folder }}.zip"
          }'
      - name: Store response payload to file
        run: echo '${{ fromJSON(steps.githubtos3.outputs.response).Payload }}' > invocation-response.json
